### ISSUE TITLE
Add support for  description, online, share_text, commands

### ISSUE THREAD

**Issue by danog** [pwrtelegram/tg#5]
Add support for  description, online, share_text, commands in the json result of the user_info, channel_info and group_info commands.
This can be done by editing https://github.com/pwrtelegram/tg/blob/master/interface.c#L2726 and https://github.com/pwrtelegram/tg/blob/master/json-tg.c#L109

**Comment by veetaw** [comment]
@danog 🌚

**Comment by kingmiladee** [comment]
Hi
﷼💮
